### ISSUE TITLE
Skill not work on docker

### ISSUE THREAD

**Issue by GoldenbyteGH** [ChristopherRogers1991/mycroft_routine_skill#11]
Hi, 
I've installed the skill on my microft-core in a docker container , but it doesn't work, if i give the commands mycroft can't understand me.

I Can see in the logs file:

```

021-06-12 18:02:09.776 | INFO     |    27 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft_routine_skill.christopherrogers1991/settings.json

  File "/opt/mycroft/skills/mycroft_routine_skill.christopherrogers1991/__init__.py", line 59, in initialize

2021-06-12 18:02:09.864 | ERROR    |    27 | mycroft.skills.skill_loader:_communicate_load_status:351 | Skill mycroft_routine_skill.christopherrogers1991 failed to load`
```

I see that _settings.json_ not exist in that folder

**Comment by ChristopherRogers1991** [comment]
Is there more to the error message? What comes after the `failed to load` line?

I think that file not existing is fine - I think Mycroft reads settings from multiple places, and that local file is just the final set of overrides. That said, you could try creating the file, and just putting `{}` in the file (an empty JSON object).

**Comment by GoldenbyteGH** [comment]
Yes I found these errors:

```
021-06-12 21:38:50.716 | INFO     |    98 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft_routine_skill.christopherrogers1991
2021-06-12 21:38:50.909 | INFO     |    98 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft_routine_skill.christopherrogers1991/settings.json
2021-06-12 21:38:50.951 | ERROR    |    98 | mycroft.skills.skill_loader:_create_skill_instance:313 | Skill initialization failed with UnknownTimeZoneError('Can not find any timezone configuration',)
Traceback (most recent call last):
  File "/opt/mycroft/mycroft/skills/skill_loader.py", line 307, in _create_skill_instance
    self.instance.initialize()
  File "/opt/mycroft/skills/mycroft_routine_skill.christopherrogers1991/__init__.py", line 59, in initialize
    self.scheduler = BackgroundScheduler()
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 87, in __init__
    self.configure(gconfig, **options)
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 126, in configure
    self._configure(config)
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/apscheduler/schedulers/background.py", line 29, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 697, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/tzlocal/unix.py", line 123, in get_localzone
    _cache_tz = _get_localzone()
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/tzlocal/unix.py", line 117, in _get_localzone
    raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')
pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'
2021-06-12 21:38:50.954 | ERROR    |    98 | mycroft.skills.skill_loader:_communicate_load_status:351 | Skill mycroft_routine_skill.christopherrogers1991 failed to load
```
The empty Json not solved.

**Comment by ChristopherRogers1991** [comment]
It looks like you need to install the tzdata package in your container. See https://stackoverflow.com/questions/21717411/timezone-information-missing-in-pytz#51317300

**Comment by GoldenbyteGH** [comment]
It Worked, thanks
