### ISSUE TITLE
Error deleting a routine

### ISSUE THREAD

**Issue by burnsfisher** [ChristopherRogers1991/mycroft_routine_skill#14]
The skill appears to delete the routine, but then throws an uncaught error. Here is the traceback:

Traceback (most recent call last):
File "/home/pi/mycroft-core/mycroft/skills/mycroft_skill/event_container.py", line 73, in wrapper
handler(message)
File "/opt/mycroft/skills/mycroft_routine_skill.christopherrogers1991/init.py", line 338, in _delete_routine
self._delete_routine_quiet(message)
File "/opt/mycroft/skills/mycroft_routine_skill.christopherrogers1991/init.py", line 346, in _delete_routine_quiet
self._show_routines()
TypeError: _show_routines() missing 1 required positional argument: 'message'
@burnsfisher

I will fix it in a few minutes.  I did so on my local system.  I'll fix it and add a pull request in a few minutes, but I wanted to record it.

**Comment by ChristopherRogers1991** [comment]
Merged the fix, thank you!
